name: Java and Gradle set up
description: Sets up the Java and Gradle
runs:
  using: "composite"
  steps:

    # Setup java
    - name: Setup JDK 17
      id: setup_jdk
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: 17

    # Copy secrets
    - name: Copy secrets
      id: copy_secrets
      shell: bash
      env:
        API_READ_ACCESS_TOKEN: ${{ secrets.API_READ_ACCESS_TOKEN }}
        DB_ENCRYPTION_PASS: ${{ secrets.DB_ENCRYPTION_PASS }}
      run: |
        touch ./local.properties
        echo api_read_access_token=\"$API_READ_ACCESS_TOKEN\" >> ./local.properties
        echo db_encryption_pass=\"$DB_ENCRYPTION_PASS\" >> ./local.properties
        cat ./local.properties

    # Setup gradle
    - name: Setup Gradle
      id: setup_gradle
      uses: gradle/gradle-build-action@v2
