name: Common Tests CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  KMP-Android:
    runs-on: macos-latest

    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - run: ./gradlew clean testDebugUnitTest -p shared/

  KMP-iOS:
    runs-on: macos-latest

    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      - run: if [[ $(uname -m) == 'arm64' ]]; then ./gradlew clean iosSimulatorArm64Test -p shared/; else ./gradlew clean iosX64Test -p shared/; fi
