name: Common Tests CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  KMP-Android:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, 'trigger build')
    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      # Copy secrets
      - name: Copy secrets
        id: copy_secrets
        shell: bash
        env:
          API_READ_ACCESS_TOKEN: ${{ secrets.API_READ_ACCESS_TOKEN }}
          DB_ENCRYPTION_PASS: ${{ secrets.DB_ENCRYPTION_PASS }}
        run: |
          touch ./local.properties
          echo api_read_access_token=\"$API_READ_ACCESS_TOKEN\" >> ./local.properties
          echo db_encryption_pass=\"$DB_ENCRYPTION_PASS\" >> ./local.properties
          cat ./local.properties

      - name: Run Common Android Unit Tests
        run: ./gradlew testDebugUnitTest -p shared/

      - name: Upload Common Android Unit Tests Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: /Users/runner/work/movieskmm/movieskmm/shared/build/reports/tests/testDebugUnitTest/

  KMP-iOS:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, 'trigger build')
    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      # Copy secrets
      - name: Copy secrets
        id: copy_secrets
        shell: bash
        env:
          API_READ_ACCESS_TOKEN: ${{ secrets.API_READ_ACCESS_TOKEN }}
          DB_ENCRYPTION_PASS: ${{ secrets.DB_ENCRYPTION_PASS }}
        run: |
          touch ./local.properties
          echo api_read_access_token=\"$API_READ_ACCESS_TOKEN\" >> ./local.properties
          echo db_encryption_pass=\"$DB_ENCRYPTION_PASS\" >> ./local.properties
          cat ./local.properties

      - name: Run Common iOS Unit Tests
        run: if [[ $(uname -m) == 'arm64' ]]; then ./gradlew iosSimulatorArm64Test -p shared/; else ./gradlew iosX64Test -p shared/; fi

      - name: Upload Common iOS Unit Tests Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path:
            /Users/runner/work/movieskmm/movieskmm/shared/build/reports/tests/iosSimulatorArm64Test/
            /Users/runner/work/movieskmm/movieskmm/shared/build/reports/tests/iosX64Test/
