name: iOS CI

on: pull_request

# Cancel any current or previous job from the same PR
concurrency:
  group: ios-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      # Copy secrets
      - name: Copy secrets
        id: copy_secrets
        env:
          API_READ_ACCESS_TOKEN: ${{ secrets.API_READ_ACCESS_TOKEN }}
        run: |
          touch ./local.properties
          echo api_read_access_token=\"$API_READ_ACCESS_TOKEN\" >> ./local.properties
          cat ./local.properties

      # Setup java
      - name: Setup JDK 17
        id: setup_jdk
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17

      # Build ios app
      - name: Build iOS app
        id: generate_debug_build
        run: xcodebuild -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 8' build



