name: iOS Tests CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  iOS:
    runs-on: macos-14
    if: contains(github.event.head_commit.message, 'trigger build')
    steps:
      # Code checkout
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Job set up
        uses: ./.github/actions/job-set-up

      # Copy secrets
      - name: Copy secrets
        id: copy_secrets
        shell: bash
        env:
          API_READ_ACCESS_TOKEN: ${{ secrets.API_READ_ACCESS_TOKEN }}
          DB_ENCRYPTION_PASS: ${{ secrets.DB_ENCRYPTION_PASS }}
        run: |
          touch ./local.properties
          echo api_read_access_token=\"$API_READ_ACCESS_TOKEN\" >> ./local.properties
          echo db_encryption_pass=\"$DB_ENCRYPTION_PASS\" >> ./local.properties
          cat ./local.properties

      - name: iOS set up
        uses: ./.github/actions/ios-set-up

      - run: xcodebuild build -allowProvisioningUpdates test -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' -verbose

#      - name: Upload logs
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          path: "/Users/runner/Library/Developer/Xcode/DerivedData/*"
